name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]

jobs:
  publish-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          cd cloudflare/worker
          # ensure wrangler.toml is populated; the action will use env CF_ACCOUNT_ID
          wrangler publish --env production
